### ISSUE TITLE
Unity 5 Terrains

### ISSUE THREAD

**Issue by hesa2020** [jlalleve/rcdtcs#2]
It doesnt seems to work for Unity 5 terrains.
Is there any possible fix ?

**Comment by jlalleve** [comment]
Hello, it seems to work but you have to change a bit the code, by default the demo application is looking for a meshfilter, look for

m_System.AddMesh(mesh, transform.gameObject);

in RcdtcsSampleSoloMesh. You'll want to call AddTerrain here instead.

Get rid of the early returns above. Also make sure the terrain is not too big (the one by default seems to take a very long time to compute).

Hope this helps
![capture d ecran 2016-07-15 a 20 06 53](https://cloud.githubusercontent.com/assets/6909785/16891475/0887bc86-4ac8-11e6-9aab-280edb6d4b74.png)

**Comment by hesa2020** [comment]
oh your right it does work, guess 500x500 terrains take to much time to compute and i wasnt patient enough.
Can you contact me on facebook please. i would have few questions for you: https://www.facebook.com/HesaOfficial
